Fix warnings for Rust 1.85.1 in system/zygote
```
FAILED: out/soong/.intermediates/system/zygote/capwrap/libcapwrap/linux_glibc_x86_64_rlib_rlib-std/libcapwrap.rlib.clippy
ANDROID_RUST_VERSION=1.85.1 out/host/linux-x86/bin/rustc_wrapper prebuilts/rust/linux-x86/1.85.1/bin/clippy-driver --emit metadata -o out/soong/.intermediates/system/zygote/capwrap/libcapwrap/linux_glibc_x86_64_rlib_rlib-std/libcapwrap.rlib.clippy --emit dep-info=out/soong/.intermediates/system/zygote/capwrap/libcapwrap/linux_glibc_x86_64_rlib_rlib-std/libcapwrap.rlib.clippy.d.raw system/zygote/capwrap/src/lib.rs --extern anyhow=out/soong/.intermediates/external/rust/android-crates-io/crates/anyhow/libanyhow/linux_glibc_x86_64_rlib_rlib-std/libanyhow.rlib --extern bitflags=out/soong/.intermediates/external/rust/android-crates-io/crates/bitflags/libbitflags/linux_glibc_x86_64_rlib_rlib-std/libbitflags.rlib --extern zygote_sys=out/soong/.intermediates/system/zygote/zygote-sys/libzygote_sys/linux_glibc_x86_64_rlib_rlib-std/libzygote_sys.rlib --extern std=prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7db8ef8b6d15f2e7.rlib -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/ -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib -L out/soong/.intermediates/external/rust/android-crates-io/crates/anyhow/libanyhow/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/libc/liblibc/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/static_assertions/libstatic_assertions/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/zerocopy/libzerocopy/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/zerocopy-derive/libzerocopy_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/libcap/libcap/linux_glibc_x86_64_shared/ -Z unstable-options -Z stack-protector=strong -Z remap-cwd-prefix=. -C debuginfo=2 -C opt-level=3 -C overflow-checks=on -C force-unwind-tables=yes -C symbol-mangling-version=v0 --color=always -Z dylib-lto -Z link-native-libraries=no -Z force-unstable-if-unmarked --cfg soong -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib32 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib64 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/lib/gcc/x86_64-linux/4.8.3 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/lib  -C relocation-model=pic -A deprecated -A unknown_lints -D missing-docs -D warnings -D unsafe_op_in_unsafe_fn --edition=2021 -C metadata=libcapwrap --crate-type=rlib --crate-name=capwrap --target=x86_64-unknown-linux-gnu --sysroot=/dev/null -C codegen-units=1 -Zallow-features="" -A clippy::disallowed_names -A clippy::empty_line_after_doc_comments -A clippy::type-complexity -A clippy::unnecessary_fallible_conversions -A clippy::unnecessary-wraps -A clippy::unusual-byte-groupings -A clippy::upper-case-acronyms -D clippy::undocumented_unsafe_blocks && grep ^out/soong/.intermediates/system/zygote/capwrap/libcapwrap/linux_glibc_x86_64_rlib_rlib-std/libcapwrap.rlib.clippy: out/soong/.intermediates/system/zygote/capwrap/libcapwrap/linux_glibc_x86_64_rlib_rlib-std/libcapwrap.rlib.clippy.d.raw > out/soong/.intermediates/system/zygote/capwrap/libcapwrap/linux_glibc_x86_64_rlib_rlib-std/libcapwrap.rlib.clippy.d
error: operator precedence can trip the unwary
   --> system/zygote/capwrap/src/lib.rs:220:17
    |
220 |                 data[0].effective as RawCap | (data[1].effective as RawCap) << 32,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `data[0].effective as RawCap | ((data[1].effective as RawCap) << 32)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence
    = note: `-D clippy::precedence` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::precedence)]`

error: operator precedence can trip the unwary
   --> system/zygote/capwrap/src/lib.rs:223:17
    |
223 |                 data[0].permitted as RawCap | (data[1].permitted as RawCap) << 32,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `data[0].permitted as RawCap | ((data[1].permitted as RawCap) << 32)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence

error: operator precedence can trip the unwary
   --> system/zygote/capwrap/src/lib.rs:226:17
    |
226 |                 data[0].inheritable as RawCap | (data[1].inheritable as RawCap) << 32,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `data[0].inheritable as RawCap | ((data[1].inheritable as RawCap) << 32)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence

error: aborting due to 3 previous errors
```

Bug: 421269002
Test: m rust
Change-Id: I7f5adb2da199d1e00a53d88240d16435ee71ff89